name: Deploy to Production

on:
  push:
    branches:
      - main

env:
  VERCEL_ORG_ID: team_4zNlTrLDYS8Zz4v7OdVHGBTl
  VERCEL_PROJECT_ID: prj_syIXQSulWzMeKiKcX9mSdsjY5Oo8

jobs:
  deploy:
    name: Deploy → Vercel (Production)
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Vercel CLI
        run: npm install --global vercel@latest

      - name: Deploy to production
        working-directory: apps/web
        run: vercel deploy --prod --token=${{ secrets.VERCEL_TOKEN }}
